---
# tasks file for sssd
- name: install sssd package
  yum:
    name: sssd
    state: present

- name: update nsswitch.conf file
  replace:
    path: /etc/nsswitch.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: "^passwd:.*", replace: "passwd: files sss" }
    - { regexp: "^shadow:.*", replace: "shadow: files sss" }
    - { regexp: "^group:.*", replace: "group: files sss" }

- name: update system-auth filei(1/2)
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^session [ ]*optional [ ]*pam_systemd.so'
    line: '-session     optional      pam_systemd.so'


- name: update system-auth filei(2/2)
  lineinfile:
    path: /etc/pam.d/system-auth
    insertafter: '-session     optional      pam_systemd.so'
    line: 'session     optional      pam_mkhomedir.so umask=0077'
    create: yes



- name: sssd conf
  template:
    src: sssd.j2
    dest: /etc/sssd/sssd.conf

- name: chmod 600 sssd.conf
  shell: 'chmod 600 /etc/sssd/sssd.conf'
  args:
    warn: false
  ignore_errors: true

- name: restart sssd
  service:
    name: sssd
    state: restarted
    enabled: true



